services:
  sintel_backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: sintel_backend
    volumes:
      - ./backend:/app
      - static_volume:/app/static
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  postgres:
    image: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  sintel_frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: sintel_frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development

  sintel_landing:
    build:
      context: ./landing_page/
      dockerfile: Dockerfile
    container_name: sintel_landing
    volumes:
      - ./landing_page:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production  # Should be 'production' for a production build


volumes:
  postgres_data:
  static_volume:
