services:
  sintel_backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: sintel_backend
    volumes:
      - ./backend:/app
      - static_volume:/app/static
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - .env
    ports:
      - "8000:8000"

  sintel_frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: sintel_frontend
    ports:
      - "5173:5173"  # use port 5173 for React app
    environment:
      - NODE_ENV=production

  landing_page:
    build:
      context: ./landing_page
      dockerfile: Dockerfile
    container_name: landing_page
    ports:
      - "3000:3000"  # Using port 3000 for Next.js landing page
    environment:
      - NODE_ENV=production
    depends_on:
      - sintel_backend

volumes:
  postgres_data:
  static_volume:
