services:
  sintel_backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: sintel_backend
    volumes:
      - ./backend:/app
      - static_volume:/app/static
      - media_volume:/app/media  # Mount media directory to persist media files
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  postgres:
    image: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  sintel_frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: sintel_frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development

  landing_page:
    build:
      context: ./landing_page
      dockerfile: Dockerfile
    container_name: landing_page
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - sintel_backend

volumes:
  postgres_data:
  static_volume:
  media_volume:  # Volume for media files
