services:
  sintel_backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: sintel_backend
    volumes:
      - .:/app
      - static_volume:/app/static
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  postgres:
    image: postgres
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: sintel_frontend
    volumes:
      - ./frontend
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development

volumes:
  postgres_data:
  static_volume:
