# Generated by Django 5.1.1 on 2024-12-02 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='note',
            field=models.TextField(default='note'),
            preserve_default=False,
        ),
    ]
