# Generated by Django 5.1.1 on 2024-11-27 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokentransaction',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
